### setup (run before hand)

In [1]:
from load_data import Signal
import cnn
import os
from glob import glob

DATASET = "emg_dataset"
glob_pattern = os.path.join(DATASET, '*')
arr = glob(glob_pattern)
print(arr[0])
datafiles = arr

emg_dataset\S11_10_KE.otb+_decomp.mat_edited.mat


### valid and invalid files

In [29]:
arr[arr.index("emg_dataset\S15_80_KE.otb+_decomp.mat_edited.mat") - 1: 36 + 2]

['emg_dataset\\S15_40_KE.otb+_decomp.mat_edited.mat',
 'emg_dataset\\S15_80_KE.otb+_decomp.mat_edited.mat',
 'emg_dataset\\S16_10_KE.otb+_decomp.mat_edited.mat']

In [29]:
count = 0
valid_files = []
invalid_files = []
for idx, file in enumerate(arr):
    file_idx = 36 + idx
    try:
        zi = Signal(file)
        #print(idx, file, zi.data.shape)
        count += 1
        valid_files.append(file)
    except Exception as e:
        print(f"\t{e}")
        print(f"\tCanot process {idx=}, {file=}")
        invalid_files.append(file)

0 emg_dataset\S11_10_KE.otb+_decomp.mat_edited.mat (256, 79616)
1 emg_dataset\S11_20_KE.otb+_decomp.mat_edited.mat (256, 98432)
2 emg_dataset\S11_30_KE.otb+_decomp.mat_edited.mat (256, 104576)
3 emg_dataset\S11_40_KE.otb+_decomp.mat_edited.mat (256, 103040)
4 emg_dataset\S11_50_KE.otb+_decomp.mat_edited.mat (256, 93184)
5 emg_dataset\S11_60_KE.otb+_decomp.mat_edited.mat (256, 104320)
6 emg_dataset\S11_70_KE.otb+_decomp.mat_edited.mat (256, 109568)
7 emg_dataset\S11_80_KE.otb+_decomp.mat_edited.mat (256, 114304)
8 emg_dataset\S12_10_KE.otb+_decomp.mat_edited.mat (256, 79360)
9 emg_dataset\S12_20_KE.otb+_decomp.mat_edited.mat (256, 88192)
10 emg_dataset\S12_30_KE.otb+_decomp.mat_edited.mat (256, 97792)
11 emg_dataset\S12_40_KE.otb+_decomp.mat_edited.mat (256, 106496)
12 emg_dataset\S12_50_KE.otb+_decomp.mat_edited.mat (256, 90496)
13 emg_dataset\S12_60_KE.otb+_decomp.mat_edited.mat (256, 102656)
14 emg_dataset\S12_70_KE.otb+_decomp.mat_edited.mat (256, 110976)
15 emg_dataset\S12_80_KE.ot

In [30]:
print(count)
print(valid_files)

104
['emg_dataset\\S11_10_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_20_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_30_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_40_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_50_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_60_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_70_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S11_80_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_10_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_20_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_30_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_40_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_50_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_60_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_70_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S12_80_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S13_10_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S13_20_KE.otb+_decomp.mat_edited.mat', 'emg_dataset\\S13_30_KE.otb+_decomp.mat_e

In [31]:
for file in valid_files:
    print(file)

emg_dataset\S11_10_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_20_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_30_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_40_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_50_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_60_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_70_KE.otb+_decomp.mat_edited.mat
emg_dataset\S11_80_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_10_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_20_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_30_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_40_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_50_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_60_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_70_KE.otb+_decomp.mat_edited.mat
emg_dataset\S12_80_KE.otb+_decomp.mat_edited.mat
emg_dataset\S13_10_KE.otb+_decomp.mat_edited.mat
emg_dataset\S13_20_KE.otb+_decomp.mat_edited.mat
emg_dataset\S13_30_KE.otb+_decomp.mat_edited.mat
emg_dataset\S13_40_KE.otb+_decomp.mat_edited.mat
emg_dataset\S13_50_K

In [33]:
for file in invalid_files:
    print(file)

emg_dataset\S16_10_KE.otb+_decomp.mat_edited.mat
emg_dataset\S16_20_KE.otb+_decomp.mat_edited.mat
emg_dataset\S16_30_KE.otb+_decomp.mat_edited.mat
emg_dataset\S16_40_KE.otb+_decomp.mat_edited.mat
emg_dataset\S16_50_KE.otb+_decomp.mat_edited.mat
emg_dataset\S16_60_KE.otb+_decomp.mat_edited.mat
emg_dataset\S16_70_KE.otb+_decomp.mat_edited.mat
emg_dataset\S17_20_KE.otb+_decomp.mat_edited.mat
emg_dataset\S17_40_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_10_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_20_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_30_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_40_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_50_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_60_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_70_KE.otb+_decomp.mat_edited.mat
emg_dataset\S18_80_KE.otb+_decomp.mat_edited.mat
emg_dataset\S4_10_DF.otb+_decomp_edited.mat
emg_dataset\S4_50_DF.otb+_decomp_edited.mat
emg_dataset\S4_60_DF.otb+_decomp_edited.mat


### spectograph processing

In [3]:
from load_data import Signal
from scipy.signal import spectrogram
import torchaudio
import torch

C:\Users\savnkk\AppData\Roaming\Python\Python310\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")


In [4]:
file = os.path.join(DATASET,"S1_10_DF.otb+_decomp.mat_edited.mat")
datafiles.index(file)

60

In [5]:
sig = Signal(file)

In [7]:
samples = []
electrodes = []

for idx, file in enumerate(arr):
    try:
        zi = Signal(file)
        print(zi.data.size)
        sample, electrode = zi.data.shape 
        electrodes.append(electrode)
        samples.append(sample)
    except Exception as e:
        print(f"\t{e}")
        print(f"\tCanot process {idx=}, {file=}")

20381696
	emg_dataset\S11_20_KE.otb+_decomp.mat_edited.mat is not a MATLAB 7.3 file. Load with scipy.io.loadmat() instead.
	Canot process idx=1, file='emg_dataset\\S11_20_KE.otb+_decomp.mat_edited.mat'
26771456
26378240
23855104
26705920
28049408
29261824
20316160
22577152
25034752
27262976
23166976
26279936
28409856
28704768
20676608
21594112
24477696
26836992
22183936
25034752
27131904
29327360
21539200
25541760
25307765
25982720
24117120
24931200
28865920
28187520
20996480
23845760
25847040
27136000
30561920
21335680
23065600
25440000
29239040
24490240
27102080
28051840
21200896
23330816
26083328
26738688
23330816
25624576
28147712
30539776
20860800
23370880
24897280
27780480
23777920
26254080
27950080
30697600
16616030
18624465
20793755
22963575
22182885
24762130
24321170
26321390
16481675
18793535
21097975
23065070
22795565
25812590
24091680
28526455
16691820
18659975
20655955
23339610
22455305
25780525
24051930
26184915
16330890
18852630
20759040
23423615
22461135
24613465
236584

In [12]:
import scipy
print(scipy.stats.describe(samples, ddof=1, bias=False))
print(scipy.stats.describe(electrodes, ddof=1, bias=False))

DescribeResult(nobs=123, minmax=(256, 265), mean=262.7317073170732, variance=15.394642143142741, skewness=-1.156384269253502, kurtosis=-0.6740028745957383)
DescribeResult(nobs=123, minmax=(61626, 119296), mean=91267.9593495935, variance=170922316.0065307, skewness=-0.3025135808301116, kurtosis=-0.30354631291591305)


In [ ]:
# get shape (electrodes, samples)
# sample 256 out of electrodes
# pad using 119296 - samples //2 on both sides
# apply fft
# transform to torch tensor

In [ ]:
tx = torch.tensor(zi.data)
transform = torchaudio.transforms.Spectrogram(n_fft=2048)
transform(tx)

In [10]:
torch.nn.functional.pad(torch.tensor([[0,1],[0,1]], dtype=torch.float64),  (5,2))

tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=torch.float64)

In [14]:
import numpy as np
np.pad(np.array([[0,1],[0,1]]),  ((0,0), (5,2)))

array([[0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [22]:
apply_spec = np.frompyfunc(lambda x: spectrogram(x, fs=2048), 1, 1)
vec_spec = np.vectorize(spectrogram)

In [16]:
SEED = 0
rng = np.random.default_rng(SEED)
print(rng.choice(zi.data.shape[0], size=10, replace=False))
x2 = zi.data[rng.choice(zi.data.shape[0], size=10, replace=False)]

[217 215 163 131  69  10   4  80  46  19]


In [18]:
print(x2.shape)

(10, 103812)


In [20]:
PAD_TARGET = 119296
pad = (PAD_TARGET - x2.shape[1])//2
print(pad)
x3 = np.pad(x2, ((0,0), (pad,pad)))
print(x3.shape)

7742
(10, 119296)


In [30]:
fin = np.zeros((10, 129, 532))
for (idx, row) in enumerate(x3):
    f, t, sxx = spectrogram(row, fs=2048)
    fin[idx] = sxx
#spec4 = vec_spec(x3, fs=2048)
print(fin.shape)

(10, 129, 532)


In [31]:
fin.dtype

dtype('float64')

### Selecting samples

In [33]:
import numpy as np
SEED = 0
rng = np.random.default_rng(SEED)
rng.choice(256, size=5, replace=False)

array([161, 129,  68,  78, 214], dtype=int64)

### testing labels

In [26]:
from load_data import Label
for file in arr:
    L = Label(os.path.basename(file))
    print(L.__dict__)

{'subject': '11', 'force': '10', 'task': 'KE'}
{'subject': '11', 'force': '20', 'task': 'KE'}
{'subject': '11', 'force': '30', 'task': 'KE'}
{'subject': '11', 'force': '40', 'task': 'KE'}
{'subject': '11', 'force': '50', 'task': 'KE'}
{'subject': '11', 'force': '60', 'task': 'KE'}
{'subject': '11', 'force': '70', 'task': 'KE'}
{'subject': '11', 'force': '80', 'task': 'KE'}
{'subject': '12', 'force': '10', 'task': 'KE'}
{'subject': '12', 'force': '20', 'task': 'KE'}
{'subject': '12', 'force': '30', 'task': 'KE'}
{'subject': '12', 'force': '40', 'task': 'KE'}
{'subject': '12', 'force': '50', 'task': 'KE'}
{'subject': '12', 'force': '60', 'task': 'KE'}
{'subject': '12', 'force': '70', 'task': 'KE'}
{'subject': '12', 'force': '80', 'task': 'KE'}
{'subject': '13', 'force': '10', 'task': 'KE'}
{'subject': '13', 'force': '20', 'task': 'KE'}
{'subject': '13', 'force': '30', 'task': 'KE'}
{'subject': '13', 'force': '40', 'task': 'KE'}
{'subject': '13', 'force': '50', 'task': 'KE'}
{'subject': '